import Head from 'next/head'
import HomePage from '@/pages/home/homePage'

export default function Home() {
  return (
    <div className='bg-base-100'>
      <Head>
        <title>New Egg BD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}
